export const EDIT_USER="USER/EDIT_USER";
export const DELETE_USER="USER/DELETE_USER";
export const GET_USER_LIST="USER/GET_USER_LIST";
export const SHOW_MODAL="USER/SHOW_MODAL";
export const HIDDEN_MODAL="USER/HIDDEN_MODAL";
export const SET_NEW_EDIT_USER="USER/SET_NEW_EDIT_USER";