export const EDIT_PRODUCT="PRODUCT/EDIT_PRODUCT";
export const DELETE_PRODUCT="PRODUCT/DELETE_PRODUCT";
export const GET_PRODUCT_LIST="PRODUCT/GET_PRODUCT_LIST";
export const SHOW_MODAL="PRODUCT/SHOW_MODAL";
export const HIDDEN_MODAL="PRODUCT/HIDDEN_MODAL";
export const GET_NEW_PRODUCTLIST="PRODUCT/GET_NEW_PRODUCTLIST";