export const EDIT_WAREHOUSE="WAREHOUSE/EDIT_WAREHOUSE";
export const DELETE_WAREHOUSE="WAREHOUSE/DELETE_WAREHOUSE";
export const GET_WAREHOUSE_LIST="WAREHOUSE/GET_WAREHOUSE_LIST";
export const SHOW_MODAL="WAREHOUSE/SHOW_MODAL";
export const HIDDEN_MODAL="WAREHOUSE/HIDDEN_MODAL";