export const EDIT_CUSTOMER="CUSTOMER/EDIT_CUSTOMER";
export const DELETE_CUSTOMER="CUSTOMER/DELETE_CUSTOMER";
export const GET_CUSTOMER_LIST="CUSTOMER/GET_CUSTOMER_LIST";
export const SHOW_MODAL="CUSTOMER/SHOW_MODAL";
export const HIDDEN_MODAL="CUSTOMER/HIDDEN_MODAL";
export const SET_NEW_EDIT_CUSTOMER="CUSTOMER/SET_NEW_EDIT_CUSTOMER";