export const SEARCH_FOCUS='header/SEARCH_FOCUS';
export const SEARCH_BLUR='HEADER/SEARCH_BLUR';
export const CHANGE_LIST='HEADER/CHANGE_LIST';
export const MOUSE_ENTER='HEADER/MOUSE_ENTER';
export const MOUSE_LEAVE='HEADER/MOUSE_LEAVE';
